#############################################################################
# Makefile for building: filesearch
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  filesearch.pro
# Template: app
# Command: /home/heineken/Programs/Qt/5.5/gcc_64/bin/qmake -spec linux-g++ -o Makefile filesearch.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../Programs/Qt/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/heineken/Programs/Qt/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = filesearch1.0.0
DISTDIR = /home/heineken/Documents/QT/testos/filesearch/.tmp/filesearch1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/heineken/Programs/Qt/5.5/gcc_64
LIBS          = $(SUBLIBS) -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.c \
		btreeindex.c 
OBJECTS       = main.o \
		btreeindex.o
DIST          = ../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		filesearch.pro btreeindex.h main.c \
		btreeindex.c
QMAKE_TARGET  = filesearch
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = filesearch


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: filesearch.pro ../../../../Programs/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf ../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/unix.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/linux.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/qconfig.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/default_post.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/yacc.prf \
		../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/lex.prf \
		filesearch.pro
	$(QMAKE) -spec linux-g++ -o Makefile filesearch.pro
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/spec_pre.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/unix.conf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/linux.conf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/sanitize.conf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/gcc-base.conf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/g++-base.conf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/common/g++-unix.conf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/qconfig.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt_functions.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt_config.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/spec_post.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/default_pre.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/resolve_config.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/default_post.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/warn_on.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/qt.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/unix/thread.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/exceptions.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/yacc.prf:
../../../../Programs/Qt/5.5/gcc_64/mkspecs/features/lex.prf:
filesearch.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile filesearch.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.c btreeindex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o main.c

btreeindex.o: btreeindex.c btreeindex.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o btreeindex.o btreeindex.c

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

